### ISSUE TITLE
Update to Sculpt 24.10

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#105]
For the upcoming Sculpt release, Goa's built-in archive versions need to be updated. In this issue, I am going to share and thereby document the update procedure.

#### Prerequisites

- Before starting the update procedure, I need to make sure that my clones of the genode and genode-world repositories are up-to-date (i.e. point to the current master branch with the updated depot recipe hashes).
- I also check whether Goa's branch for the current version (in this case _24.04_) can be fast-forwarded to the _master_ branch (or any reasonable state in between). This makes sure that users can seamlessly switch between Sculpt versions via `goa update <version>` and get the lastest compatible Goa state when executing, e.g., `goa update 24.04`.

#### Updating archive versions

- For getting the updated archive versions, I use the `goa archive-versions` command in combination with the meta archive in my [goa-projects repository](https://github.com/jschlatow/goa-projects/).
- In order to export the versions into a temporary file _/tmp/current_, I execute the following command:
```
goa-projects/$ goa -C meta/goa archive-versions --versions-from-genode-dir ~/repos/genode | column -t > /tmp/current
```
- Next, I edit remove comments, the versions after `# additional depot-archive  versions from  goarc` and trailing whitespace.
- Using vimdiff, I merge the file with _share/goa/goarc_ from the Goa repository.

#### Testing

- A brief test (by executing _share/goa/lib/test.expect_) should be run before staging any changes.

**Comment by cproc** [comment]
Commit ee68200 removes the `_drv` suffix.

**Comment by jschlatow** [comment]
> Commit [ee68200](https://github.com/genodelabs/goa/commit/ee68200a92928460e62b66249e399accf5acd25c) removes the `_drv` suffix.

Thanks for the fix!
