### ISSUE TITLE
Add Qt6 support

### ISSUE THREAD

**Issue by cproc** [genodelabs/goa#106]

**Comment by cproc** [comment]
Fixed by d82655f. There are no Qt6 depot archives published by `genodelabs` yet, so I did not add a Qt6 example, but I have some ports of existing Genode Qt examples in my [goa-projects](https://github.com/cproc/goa-projects/tree/staging) repository which I tested with local depot archives so far.

**Comment by jschlatow** [comment]
Awesome! Merged to staging with fixup 6e4c30b for error handling.
