### ISSUE TITLE
running goa from relative path

### ISSUE THREAD

**Issue by johannesloetzsch** [genodelabs/goa#108]
At the moment goa doesn't seam to work, when the goa executable is started from a relative path.

I run into the issue, doing the following steps:

```sh
git clone git@github.com:genodelabs/goa.git
cd examples/hello_make
../../bin/goa build
```

I received this error message:

```
/nix/store/xdck1zw3ms4r1ar3xhmxvn2k3d8l0pd1-genode-toolchain-bin/bin/../lib/gcc/x86_64-pc-elf/12.3.0/../../../../x86_64-pc-elf/bin/ld: cannot open linker script file ../../share/goa/ld/genode_dyn.dl: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [<builtin>: hello] Error 1
[hello_make] Error: build via make failed
```

It turns out, that `./var/build/x86_64/.goa_make_command` contains `-Wl,--dynamic-list=../../share/goa/ld/genode_dyn.dl`.

A workaround is not calling `../../bin/goa build`, but:
```sh
$(realpath ../../bin/goa) build
```

**Comment by jschlatow** [comment]
@johannesloetzsch Thanks for reporting this. I pushed a fix to staging. Please feel free to give 490ee51 a try.
