### ISSUE TITLE
Please add example for virtualization

### ISSUE THREAD

**Issue by l-johanson** [genodelabs/goa#26]
Is Virtualbox supported for testing with `goa run`?
I've mostly just tried to run the example from: https://github.com/genodelabs/genode/tree/master/repos/ports/recipes/pkg/vbox5

I currently use the following `pkg/vbox_test/runtime`:

```
<runtime ram="4300M" caps="2500" binary="init">

        <requires>
                <file_system label="vm"/>
                <file_system label="shared"/>
                <vm/>
                <timer/>
                <gui/>
                <nic/>
                <rom label="capslock"/>
                <report label="shape"/>
                <report label="clipboard"/>
                <rom    label="clipboard"/>
                <rm/>
                <rtc/>
                <rom label="usb_devices"/>
                <usb/>
        </requires>

        <config verbose="yes">

                <parent-provides>
                        <service name="ROM"/>
                        <service name="PD"/>
                        <service name="RM"/>
                        <service name="CPU"/>
                        <service name="LOG"/>
                        <service name="VM"/>
                        <service name="Gui"/>
                        <service name="Timer"/>
                        <service name="Rtc"/>
                        <service name="Report"/>
                        <service name="File_system"/>
                        <service name="Usb"/>
                        <service name="Nic"/>
                </parent-provides>

                <default-route> <any-service> <parent/> <any-child/> </any-service> </default-route>

                <default caps="100"/>

    <start name="vfs" caps="400">
        <resource name="RAM" quantum="10M"/>
        <provides><service name="File_system"/></provides>
        <config>
            <vfs>
                <ram/>
                <rom name="machine.vbox"/>
            </vfs>
            <default-policy root="/" writeable="yes"/>
        </config>
        <route>
            <any-service> <parent/> <any-child/> </any-service>
        </route>
    </start>

                <start name="vbox" caps="2000">
                        <binary name="virtualbox5" />
                        <resource name="RAM" quantum="4G"/>
                        <exit propagate="yes"/>
                        <config vbox_file="machine.vbox" xhci="yes" vm_name="linux" capslock="ROM">
                                <vfs>
                                        <dir name="dev">
                                                <log/>
                                                <rtc/>
                                         </dir>
                                        <dir name="shared"> <fs label="shared" writeable="yes"/> </dir>
                                        <fs writeable="yes"/>
                                </vfs>
                                <libc stdout="/dev/log" stderr="/dev/log" rtc="/dev/rtc"/>
                        </config>
                        <route>
                                <service name="Audio_out"> <parent/> </service>
                                <service name="File_system" label="shared"> <parent label="shared"/> </service>
                                <service name="File_system">                <child name="vfs"/> </service>
                                <service name="ROM" label="usb_devices"> <parent label="usb_devices"/> </service>
                                <service name="ROM" label="capslock"> <parent label="capslock"/> </service>
                                <service name="ROM" label="platform_info">
                                        <parent label="platform_info"/> </service>
                                <service name="Nic"> <parent/> </service>
                                <service name="Report" label="shape"> <parent label="shape"/> </service>
                                <service name="ROM"    label="clipboard"> <parent label="clipboard"/> </service>
                                <service name="Report" label="clipboard"> <parent label="clipboard"/> </service>
                                <service name="Gui"> <parent label=""/> </service>
                                <any-service> <parent/> </any-service>
                        </route>
                </start>
        </config>

        <content>
                <rom label="ld.lib.so"/>
                <rom label="init"/>
                <rom label="virtualbox5"/>
                <rom label="libc.lib.so"/>
                <rom label="libm.lib.so"/>
                <rom label="libiconv.lib.so"/>
                <rom label="libyuv.lib.so"/>
                <rom label="qemu-usb.lib.so"/>
                <rom label="stdcxx.lib.so"/>
                <rom label="vfs.lib.so"/>
                <rom label="jpeg.lib.so"/>
                <rom label="platform_info"/>
                <rom label="machine.vbox"/>
                <rom label="vfs"/>
        </content>

</runtime>
```

The following `pkg/vbox_test/archives`:

```
TLC62CsRraK4hdw6/src/vbox5
TLC62CsRraK4hdw6/src/libc
TLC62CsRraK4hdw6/src/init
TLC62CsRraK4hdw6/src/posix
TLC62CsRraK4hdw6/src/zlib
TLC62CsRraK4hdw6/src/libiconv
TLC62CsRraK4hdw6/src/libyuv
TLC62CsRraK4hdw6/src/stdcxx
TLC62CsRraK4hdw6/src/vfs
TLC62CsRraK4hdw6/src/jpeg
```

The following `raw/platform_info` (since I read it's not provided on Linux? taken from https://github.com/genodelabs/genode/blob/master/repos/os/run/vmm_x86.run#L75 :
```
                        <platform_info>
                                <kernel name="nova"/>
                                <acpi revision="2" rsdt="0x2ffe20c5"/>
                                <affinity-space width="2" height="2"/>
                                <boot/>
                                <hardware>
                                        <features svm="true" vmx="true"/>
                                        <tsc invariant="false" freq_khz="2555589"/>
                                        <cpus>
                                                <cpu id="0" package="0" core="0" thread="0" family="0x10" model="0x2" stepping="0x3" platform="0x0" patch="0x0"/>
                                        </cpus>
                                </hardware>
                        </platform_info>
```

And a `machine.vbox` from https://github.com/genodelabs/genode/blob/master/repos/gems/recipes/raw/download_coreplus/machine.vbox

The following is output by `goa run`:

```
Genode sculpt-22.04 <local changes>
17592186044415 MiB RAM and 18997 caps assigned to init
[init -> nic_drv] MAC address 02:00:00:00:00:01
[init -> nic_drv] using tap device "tap0"
[init -> nic_drv] Error: could not configure /dev/net/tun: no virtual network emulation
terminate called after throwing an instance of 'Genode::Exception'
[init -> vbox_test] parent provides
[init -> vbox_test]   service "ROM"
[init -> vbox_test]   service "PD"
[init -> vbox_test]   service "RM"
[init -> vbox_test]   service "CPU"
[init -> vbox_test]   service "LOG"
[init -> vbox_test]   service "VM"
[init -> vbox_test]   service "Gui"
[init -> vbox_test]   service "Timer"
[init -> vbox_test]   service "Rtc"
[init -> vbox_test]   service "Report"
[init -> vbox_test]   service "File_system"
[init -> vbox_test]   service "Usb"
[init -> vbox_test]   service "Nic"
[init -> vbox_test] child "vfs"
[init -> vbox_test]   RAM quota:  9992K
[init -> vbox_test]   cap quota:  366
[init -> vbox_test]   ELF binary: vfs
[init -> vbox_test]   priority:   0
[init -> vbox_test]   provides service File_system
[init -> vbox_test] child "vbox"
[init -> vbox_test]   RAM quota:  4194056K
[init -> vbox_test]   cap quota:  1966
[init -> vbox_test]   ELF binary: virtualbox5
[init -> vbox_test]   priority:   0
[init -> vbox_test] child "vfs" announces service "File_system"
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Authorization required, but no authorization protocol specified
[init -> drivers -> fb_sdl] Error: fb_sdl works on X11 only. Your SDL backend is offscreen.
terminate called after throwing an instance of 'Sdl_videodriver_not_supported'
[init -> vbox_test -> vbox] Log created: 2023-01-21T15:24:00.002000000Z
[init -> vbox_test -> vbox] main     Executable: /virtualbox
[init -> vbox_test -> vbox] Error: SystemPropertiesWrap : Cannot determine default Guest Additions ISO location. Most likely they are not available
[init -> vbox_test] child "vbox" requests resources: cap_quota=4
```

And then it's just stuck there.

Please either document that virtualization is not possible or provide an example in this repository.

Thanks for the great work!

**Comment by nfeske** [comment]
Thanks for giving Goa a try and for the excellent report. It is amazing that you got that far.

Unfortunately, however, the Linux version of Genode - which you are using with `goa run` - is not able to run VirtualBox. This would require an implementation of Genode's VM session interface for Linux KVM. Since Genode is primarily targeted at microkernels, we have not pursued this direction. For running VirtualBox on top of Genode, I recommend the NOVA kernel as used for the official Sculpt OS images.

Could you give me a hint about where would be the best place to document the supported scope and current limitations of Goa?

**Comment by l-johanson** [comment]
Thanks for the fast and detailed response.

I see three options here:
1. Have a section called `Limitations` below the section `Usage` in the `README` file. Describe what interfaces have limited or no possible usage on the Linux version of Genode.
2. Instead of documenting the limitations, throw a runtime error, when `init` enumerates sessions it can not provide in the node `parent-provides`. In this case the `VM`-Session.
3. Instead of documenting the limitations, throw a build error, when a depot package is used, which has unresolved dependencies. In this case, VMMs like `src/vbox5` would need to depend on one of the supported kernels.

Option 2 sounds to me like a must have anyway, since as a user and developer, having a component pretending to provide sessions it actually can not, feels like unexpected behaviour. So I would go with that one.

What would you prefer / see as most user/developer friendly?

**Comment by nfeske** [comment]
Thanks for sharing your line of thoughts. I agree that option 2 is the most sensible one. Option 1 would most certainly remain unnoticed by most, whereas option 3 smells like heuristics that may be burden to maintain down the road.

I wonder, would you like to give option 2 a go, or would you prefer me implementing this?

Implementation-wise, I think it comes down to adding a check similar to https://github.com/nfeske/goa/blob/master/share/goa/lib/run/linux.tcl#L25 (backing out with `exit_with_error`). The detection of the use of the VM-session can be done with a call of `query_node /runtime/requires/vm`.

**Comment by l-johanson** [comment]
Thanks for the pointers and chance to contribute.
Since there are a couple more things I'd like to extend `goa` with, I'll gladly give it a go to gain some practice.
Though due to other responsibilities, it might take a bit.

**Comment by nfeske** [comment]
I very much appreciate your forthcoming response.

Please take your time. We are not in a hurry after all. :-)

Btw, this issue made me thinking about other session interfaces as well. There are quite a few further peculiarities when using base-linux. E.g., the attempt to create an io_mem, irq, platform, or usb session will fail ungracefully as well. So once the immediate issue is addressed, I plan to do an inventory of the various session interfaces when used with `goa run` on base-linux.

**Comment by l-johanson** [comment]
It seems, I failed to correctly reference the ticket in my pull request. Here it is: #31 

Among extending the validation, I did some refactorings, which include Tcl namespaces. The language was very easy to learn, but as a newcomer to it, I had a very hard time grasping the scope of each variable and where certain methods called come from. I expect better readability of the code might help other people contribute to the project as well!
(All in all in took me 2 days to learn Tcl and extend the project.)

I hope it's not too much change for one pull request. If necessary, I may split it up.

In another pull request, I'd like to enable `qemu` as a possible runtime, so I can run my component in a test scenario in `goa` compared to how I ran a test scenario in the context of the `genode`-repository.

**Comment by nfeske** [comment]
@l-johanson, please see https://github.com/nfeske/goa/pull/31#issuecomment-1494515676 for my comments regarding your changes.

**Comment by nfeske** [comment]
Please note that the goa repository has been moved from nfeske/goa to genodelabs/goa.

**Comment by jschlatow** [comment]
Closing this issue because
- Goa now checks the required services and provides a corresponding messages if a service has limited support or is not supported at all.
- `goa help targets` documents what services are available on the default linux target.
- The most recently added target "sculpt" can be used for test-running scenarios that require the VM service.
