### ISSUE TITLE
Fix Goa for dynamic binaries

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/goa#30]
Commit https://github.com/nfeske/goa/commit/60ef785cefedaa935a118addd34c7e2fe311f080 breaks qmake (ldlibs_exe missing) and Genode dynamic binaries (`Component::construct` gets garbage collected by `ld`, leading to broken binaries).

**Comment by ssumpf** [comment]
899c6c5 fixes qmake. d70baad and dfe434b fix dynamic binaries.

**Comment by trimpim** [comment]
@ssumpf I have tested the current master, and my build of libraries still works.
