### ISSUE TITLE
Throw an error on sessions that can not be provided from "requires" node

### ISSUE THREAD

**Issue by l-johanson** [genodelabs/goa#34]
Analog to the extended validation of elements in the `<parent-provides>`-node in `runtime`-files worked on in #26 , I would like to extend the validation to throw an error on sessions from the `<requires>`-node, which can not be provided.

For example the following `vm` session reference would not trigger a validation error in the `runtime`-file:
```
<requires>
    <vm/>
    <timer/>
</requires>
```

This would speed up debugging for users a lot and especially help eliminating first frustrations with the tooling.

Would you like to implement this or if not, are there any valuable hints you might give me concerning the implementation?

Kind regards,
Lars

**Comment by jschlatow** [comment]
Fixed by #44
