### ISSUE TITLE
add support for building Rust projects with Cargo

### ISSUE THREAD

**Issue by atopia** [genodelabs/goa#35]
- add a heuristic to detect Rust projects via presence of `Cargo.toml` in the source directory
- implement a little helper to generate dummy static libraries that satisfy linking requirements of the Rust toolchain
- add support for cargo as a build system
- add a Rust hello world example

**Comment by jschlatow** [comment]
@atopia Thanks for adding Rust support to Goa. As a first time rust/cargo user giving the hello_rust project a spin, I am facing the following error:

```
[hello_rust:stubs] make: Nothing to be done for 'default'.
error[E0463]: can't find crate for `std`
  |
  = note: the `x86_64-unknown-freebsd` target may not be installed
  = help: consider downloading the target with `rustup target add x86_64-unknown-freebsd`

error: cannot find macro `println` in this scope
 --> src/main.rs:2:5
  |
2 |     println!("Hello Genode Rust world!");
  |     ^^^^^^^

error: requires `sized` lang_item

For more information about this error, try `rustc --explain E0463`.
error: could not compile `hello-rust` due to 3 previous errors
```

Do I need to perform any preparatory steps other than installing cargo?

**Comment by atopia** [comment]
Hi Johannes, the error happens because you don't have the std library for the FreeBSD target triple installed. ***However, simply installing the binary version available from the Rust project won't work***, because it currently tries to resolve versioned symbols, which is not implemented in our linker. Right now the workaround would be to distribute a custom version of the Rust toolchain where this problem is sidestepped. The matter is still under investigation in that I want to see if I can somehow distribute a custom std library without distributing a custom compiler or if building the needed standard library parts from source when compiling a cargo project is a viable alternative. If you want I can upload the toolchain for you, additionally you'll need an extended libc available here: https://github.com/atopia/genode/tree/rust-lib-support

**Comment by jschlatow** [comment]
@atopia, after installing your custom Rust tool chain and building the modified libc, your example works. Let me know when you consider your changes ready to be merged.

**Comment by jschlatow** [comment]
@atopia I just pushed 9f6a72c to my rust_support branch in order to address a few minor style issues.

**Comment by atopia** [comment]
@jschlatow from my side you can merge my commit and your fixup.
