### ISSUE TITLE
qt5/qml: add support for qt5/qml/ubuntu ui examples

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/goa#36]
The examples can be found at https://github.com/ssumpf/goa-projects and are used to demonstrate Genode's Phone SDK.

**Comment by ssumpf** [comment]
@jschlatow: The commit above contain everything to get  https://github.com/ssumpf/goa-projects working (with run and as packets for the PinePhone). Please consider for staging.

**Comment by ssumpf** [comment]
@jschlatow: d5abd83 removes the unnecessary `VERBOSE=/-s`.

**Comment by jschlatow** [comment]
@ssumpf I gave your goa-projects a spin. When executing `goa run` with a clean 'var' directory, unit-converter fails with the following errors:

```
17592186044415 MiB RAM and 18997 caps assigned to init
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
[init] Error: unit-converter: environment ROM session denied (label="unit-converter", ram_quota=6144, cap_quota=3, diag=0)
```

The same happens for ubuntu_ui_toolkit_gallery. Interestingly, when running `goa run` a second time, the component starts successfully.

**Comment by ssumpf** [comment]
@jschlatow: Found the reason for the missing ROM links in var/bin: The depot archives are downloaded after the configuration of the runtime config, so the runtime files are not found and the ROMs within them are missing. On next run the runtimes are found and the links are created. 26fa041 fixes this and [e315388](https://github.com/ssumpf/goa/commit/e31538827f698a8cf27bb554a756bdc64603c0a8) is obsolete. I have updated my issue36_sdk-23.04 accordingly.

**Comment by jschlatow** [comment]
Thanks for the fix. Merged to staging.

Out of curiosity: The performance of the unit_converter seems quite bad. It reports frame rendering times between 1000 and 2500ms. Do you have similar issues?

**Comment by ssumpf** [comment]
@jschlatow: The toolkit does perform badly with Mesa's software rendering, it's meant for GPU rendering, but I think for development it is good enough.

**Comment by jschlatow** [comment]
The commits entered the master branch.
