### ISSUE TITLE
Add support for using another depot user's archives for `Goa run`

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#40]
Since the genodelabs depot archives needed for `goa run` are only published for the official Sculpt releases, testing/developing for other Genode versions is quite cumbersome. Having a way to configure that the required depot archives shall be taken from another user than genodelabs will greatly simplify this.

Note this configuration is different from the `depot_user` variable, which defines the depot user for exporting/publishing. The new variable should only affect the archives loaded by `goa run`. The archives referenced by any Goa package will remain unaffected by this.

Regarding the naming, I am open to suggestions. Maybe something along the line of `run_as` or `run_as_depot_user`.

@nfeske, @ssumpf Any suggestions?

**Comment by nfeske** [comment]
> Any suggestions?

I'd probably just add `run` as suffix to the respective config variable (`depot_user_run`) and command-line argument (`--depot-user-run`) but I'd be fine with your suggestion as well.
