### ISSUE TITLE
Remove wrong API export code

### ISSUE THREAD

**Issue by trimpim** [genodelabs/goa#47]
@jschlatow noticed in  https://github.com/genodelabs/goa/commit/60ef785cefedaa935a118addd34c7e2fe311f080#r117846730 that there is an artifact that exports the `API`  to the wrong location.

The code in question looks like an artifact of integrating the possibility to build libraries.  It is not needed to successfully  build our test scenario, which uses  libraries.

**Comment by jschlatow** [comment]
@trimpim Thanks for the fix which I just merged to staging.

fyi, I also added a few improvements: The api export now respects the `common_var_dir` configuration and `--common-var-dir` option. Moreover, I added the support for publishing the exported api archives.
