### ISSUE TITLE
Remove need to supply api version when exporting a non-library project

### ISSUE THREAD

**Issue by nfeske** [genodelabs/goa#48]
Goa unexpectedly requires an API version when exporting a regular src project.

This can be observed when removing the goa/examples/hello_make/version file and issuing the following commands:

```
goa/examples/hello_make$ rm version
goa/examples/hello_make$ touch /tmp/license
goa/examples/hello_make$ goa export --depot-user x --depot-overwrite --license /tmp/license 
Error: version for archive x/api/hello_make undefined
 
 Create a 'version' file in your project directory, or 
 define 'set version(x/api/hello_make) <version>' in your .goarc file.
```

In this case, Goa should only require version for x/src/hello_make, not for an API archive.

**Comment by jschlatow** [comment]
Fixed by a3da892
