### ISSUE TITLE
accessing externally provided ROM modules

### ISSUE THREAD

**Issue by trimpim** [genodelabs/goa#55]
This allows access to ROM modules that are provided from outside of the project. The feature is activated as in the code snippet below:

```
<requires>
    <rom label="name_of_rom"/>
</requires>
```

To provide the ROM a `lx_fs` and a `fs_rom` component are started. A file with the name `name_of_rom` is expected in the sub directory `roms`.

**Comment by jschlatow** [comment]
@trimpim Thanks for your contribution. Please have a look at my comments in commit 279f156.

Would you be interested in implementing a similar mechanism for Report service requirements as well?

**Comment by trimpim** [comment]
@jschlatow I just pushed 3 fixup commits. 
 - 6d3f4f9 moves the the the external ROM provider after the clipboard and removes the one variable
 - 402ffbc removes the check and removes the elements from the `services(rom)` array
 - bdaa3ed changes the indentation of the ROM provider components to match that of other similar components.

**Comment by nfeske** [comment]
Thanks for this very useful addition to Goa!

As a minor suggestion, could we rename "roms" to "rom" to stay consistent with the naming throughout Genode? 

We usually don't name things in plural (e.g., depot "image" instead of "images") with "src/drivers" being the only exception (which will hopefully rectified down the road - https://github.com/genodelabs/genode/issues/4420#issuecomment-1438629544).

**Comment by trimpim** [comment]
@nfeske is 8df4759 what you had in mind?

**Comment by trimpim** [comment]
@jschlatow about your question regarding implementing the same for the `Report` service. I currently have too many other things on my open list. Therefore I'm able to do this in the foreseeable future.

**Comment by nfeske** [comment]
> @nfeske is https://github.com/genodelabs/goa/commit/8df47590b904c0ea596fa8cdaabba3831a9fd2e1 what you had in mind?

Almost. The directory var/roms/ should be var/rom/. The `start_roms_provider` function should be named `start_rom_provider`. The name of the example comes to mind (which coincidentally only accesses one external ROM anyway). It'd probably be best to `grep` and `find` for `roms` to get all places covered.

**Comment by trimpim** [comment]
@nfeske and @jschlatow c0e070f adds the actual file for the test. It didn't get added as before, as the var directory is in `.gitignore` but it is required for the test.

**Comment by jschlatow** [comment]
@trimpim thanks a lot for the fixups. I have two more comments:

- Can you also rename the subdirectory of `external_rom/pkg`?
- Can you put the `set version ...` done in the `.goarc` into `share/goa/goarc` instead? The latter file is updated for every Sculpt release whereas we would most certainly miss updating the local `.goarc` file.
- I was quite surprised that the report_rom misses the last character when printing the report content. When I use a rom_logger to print it, it's complete though. Apparently, it must have something to do with how the report_rom does the logging. @nfeske Do you have any clue?

**Comment by trimpim** [comment]
@jschlatow happy to help.
 - 8246fee renames the sub directory of `external_rom/pkg/`
 - e494159 moves the `set version ...` to `share/goa/goarc` and removes the `.goarc` file

**Comment by jschlatow** [comment]
Merged to staging as 2f54345

**Comment by ssumpf** [comment]
```
[init -> external_rom -> report_rom]   <input>
[init -> external_rom -> report_rom]   	<hello value="Genodians"/>
[init -> external_rom -> report_rom]   </input
```
just out of curiosity does any one know why the last `>` of the output is always missing (e.g. `</intput` or `</empty`)?

**Comment by trimpim** [comment]
@ssumpf to me this sounds like it is related to https://github.com/genodelabs/genode/issues/4985

**Comment by jschlatow** [comment]
> @ssumpf to me this sounds like it is related to [genodelabs/genode#4985](https://github.com/genodelabs/genode/issues/4985)

Exactly!
