### ISSUE TITLE
document structure of 'import' files

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#56]
Currently, there is no reference in Goa where to find documentation about the structure of 'import' files. Since Goa uses the port tools from the Genode repo, the guide at [genode.org](https://genode.org/documentation/developer-resources/porting_dosbox) can be used as documentation. However, this is not immediately clear for newcomers.

Instead, I'd rather integrate documentation in terms of a `goa help import` sub-command into Goa, similar to `goa help artifacts`. This way Goa becomes more self-contained in terms of documentation.

**Comment by nfeske** [comment]
This makes perfect sense. Very nice!
