### ISSUE TITLE
run-stage: start a `nic_router` and a `nic_drv` for each required `<nic label=""/>`

### ISSUE THREAD

**Issue by trimpim** [genodelabs/goa#57]
To simplify testing of projects that use multiple NIC interfaces we should start a `nic_router` and a`nic_drv` for each required `<nic label=""/>`.

This comes from the discussion on the mailing list see:  https://lists.genode.org/pipermail/users/2023-June/008754.html

**Comment by jschlatow** [comment]
@trimpim I just pushed two commits: one that adds support for multiple nic requirements and another one for changing the naming scheme for the used tap devices.

**Comment by trimpim** [comment]
@jschlatow I have tested your commits.

f0ebcae fixes the following issues:
 - `<binary name="nic_router"/>` missing for nic_routers
 - all nic_drvs started as `<start name="nic_drv".../>`

I have reduced the number of arguments in the call to `_instantiate_network` by replacing `tap_name` and `router_name` with only label and calculating them in the procedure.

**Comment by jschlatow** [comment]
@trimpim I guess I was a bit hasty yesterday. Thanks for the fixup. I split it into 2f1d606 and b0daa7a because I'd like to keep the change of the tap device names as a separate commit. I also added some modifications:
- `instantiate_network` now returns the router name so that we don't need to assemble it at two different places
- I also fixed the `<policy label="nic_drv -> ".../>` in the router config.

**Comment by jschlatow** [comment]
@trimpim I actually like the suggestion from @nfeske on the mailing list about using a separate XML attribute to explicitly specify the tap-device name. This not only avoids introducing a convention but also allows a larger variety of scenarios, e.g. different nic requirements could be assigned to the same virtual network by using the same tap name. Internally, Goa will only instantiate a single pair of nic driver and nic router for each distinct tap device. Do you have anything to add?

**Comment by trimpim** [comment]
@jschlatow I'm fine with that. I will gladly test the changes with our scenario.

**Comment by jschlatow** [comment]
@trimpim I've force pushed a new commit 00061cb.
