### ISSUE TITLE
cargo: add static versioned stat() and fstat() symbols

### ISSUE THREAD

**Issue by atopia** [genodelabs/goa#61]
Due to ABI changes in FreeBSD 12, the libc crate used by rustc currently tries to link against versioned symbols of some library functions to preserve compatability with FreeBSD 11.

To make the standard library distributed with the `x86_64-unknown-freebsd` target work, statically link versioned stat() and fstat() symbols from the the `compat-libc` api package.

**Comment by atopia** [comment]
Thanks a lot for the `compat-libc` implementation @ssumpf!
@nfeske I hope this implements your suggestion for a static library package correctly.
@jschlatow please have a look if you find the Goa side of the implementation acceptable.

**Comment by jschlatow** [comment]
@atopia Looks reasonable from my perspective. Would you mind squashing your commits and changing the commit messages accordingly? I was first puzzled by the fork problem only to see that it was resolved by a later commit.

**Comment by chelmuth** [comment]
@atopia your topic branch for genode contains two commits for this issue. What is your merging plan? In my opinion these commits do not affect any other Genode component and could be merged until tomorrow.
