### ISSUE TITLE
Qt5: Adjust to 23.05 tool chain + add shared library support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/goa#66]

**Comment by ssumpf** [comment]
@jschlatow: Please consider b6da5df for staging.

**Comment by jschlatow** [comment]
merged to staging

**Comment by ssumpf** [comment]
@jschlatow: We experienced the "--whole-archive" problem with `libgcc.a` again with shared libraries and Qt5, same as with `cmake`. So 8f3af6e is a necessary follow up.

**Comment by chelmuth** [comment]
@ssumpf shared libraries in the genode mk link with libgcc outside of `--whole-archive --start-group ... --end-group --no-whole-archive` in *repos/base/mk/lib.mk*. Can you tell why it is not needed there but here? Note, I also checked a build of *app/texedit*, which builds *libQt5Gui.lib.so* etc.

**Comment by ssumpf** [comment]
> @ssumpf shared libraries in the genode mk link with libgcc outside of `--whole-archive --start-group ... --end-group --no-whole-archive` in _repos/base/mk/lib.mk_. Can you tell why it is not needed there but here? Note, I also checked a build of _app/texedit_, which builds _libQt5Gui.lib.so_ etc.

@chelmuth: Because there is only one archive (`libgcc.a`) there.

From the ld man page of `--start-group`
```
The specified archives are searched repeatedly until no new undefined references  are  created.
Normally,  an  archive  is  searched only once in the order that it is specified on the command
line.
```
