### ISSUE TITLE
import: patch order messed up with make 4.4

### ISSUE THREAD

**Issue by trimpim** [genodelabs/goa#67]
While testing the update to 23.10 on my new computer I noticed that sometimes patches were applied in the wrong order. I did not notice this on older make versions.

**Comment by jschlatow** [comment]
@trimpim Thanks for the fix. I had a look into the install.mk and tried to come up with a way to only serialize the patches and still allow parallel downloads for instance. Could you give c628b1f a try?

**Comment by trimpim** [comment]
@jschlatow I tested your patch, and it fixes the Issue, thanks.
