### ISSUE TITLE
exported used_api file unnecessarily omits depot-user specification

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#72]
In context of #71, I came across b23cc53, which directed my attention towards the way Goa assembles the _used_api_ file of src archives. Currently, Goa uses the archives mentioned in the project's _used_api_ file as a blueprint in order to populate the user's depot with the same api archives (if not already present). This may lead to inconsistencies if the depot user's archives actually differ.

Initially, I thought this was motivated by the limitation of the depot tools not supporting the `<user>/api/<name>/<version>` notation. By looking into the depot tools, however, I noticed that this notation is actually supported (see genodelabs/genode@1b96d0169028b0d4d59bfd5d15ba138652745833).

@cproc, @nfeske: Is there another rationale behind b23cc53 that I may have overlooked?

**Comment by cproc** [comment]
I can't remember, but It looks like https://github.com/genodelabs/genode/commit/1b96d0169028b0d4d59bfd5d15ba138652745833 was added later (2022) than b23cc53 (2020). So maybe it actually was implemented that way because of the limitation back then.
