### ISSUE TITLE
Support adding UDP/TCP forwarding rules via runtime

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#78]
In the scope of developing the goa_testbed subsystem for #77, it became apparent that having the ability to specify forwarding rules would come in handy and remove the need for writing dedicated test environments. As it turned out, we can simply add the necessary information as sub nodes to the `<nic/>` requirement in the _runtime_ file and let them be interpreted by the linux run target.

**Comment by jschlatow** [comment]
This feature is implemented by fc0a2c7. See `goa help targets` for more details. A usage example can be found in my [goa-projects](https://github.com/jschlatow/goa-projects/blob/goa_testbed/sculpt/goa_testbed/pkg/goa_testbed/runtime) repository.

**Comment by nfeske** [comment]
I love how the runtime files have become such natural hook to express environmental requirements like this.
