### ISSUE TITLE
Make '-std=gnu++20' configurable

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/goa#85]
Currently Goa hard codes `-std=gnu++20` in _flags.tcl_. Ported software might require an older C++ standard and not compile. Therefore, it would be nice to make the standard configurable.

**Comment by ssumpf** [comment]
4d541f9 implements one of the possible solutions.

**Comment by nfeske** [comment]
That looks sensible to me.

**Comment by jschlatow** [comment]
Merged to staging
