### ISSUE TITLE
inconsistency with the tutorial (unexpected diagnosic message)

### ISSUE THREAD

**Issue by nfeske** [genodelabs/goa#87]
I got the report that the current version of Goa behaves slightly different from the description given in the first tutorial (http://genodians.org/nfeske/2019-11-25-goa).

Right at the beginning of the "A first example, using a plain old Makefile" section, the tutorial tells that the following message is printed.

```
[hello] Error: hello has a 'src' directory but lacks an 'artifacts' file.
                You may start with an empty file.
```

This was the case for 23.11 (the version I used for the most recent update of the tutorial). In the new version, Goa merely tells that the directory is not a Goa project.

```
[hello] Error: hello does not look like a goa project
```

I think it would be nice to recover the more instructive message of the previous version.

**Comment by jschlatow** [comment]
I agree. I had to move the instructive message to the build stage to cover the case that `goa import` creates the _src/_ directory. However, in this attempt, I accidentally disarmed the message for projects without an _import_ file.
