### ISSUE TITLE
Old xmllint versions do not separate --xpath matches by newline

### ISSUE THREAD

**Issue by chelmuth** [genodelabs/goa#89]
I experienced strange errors due to empty `required_services` arrays, which stemmed from an old xmllint/libxml2 version (2.9.4). Tests with version 2.9.10 succeeded.

Commit 6d5dd781490f0de698ab361e663e9060d1ce270b fixed my `goa run` but there might exists other places in goa that depend on the newlines.

**Comment by jschlatow** [comment]
I consulted the changelog: The newlines for `xmllint --xpath` have been added in version 2.9.9.

**Comment by jschlatow** [comment]
@chelmuth Unfortunately, your fix breaks #78. There seems to be no easy way to separate the matches in the output of versions prior to 2.9.9. Do we actually need support for those versions in Goa? An alternative would be to detect the version and warn the user instead. I think only Debian buster and Ubuntu 18.04 are affected.

**Comment by chelmuth** [comment]
If it's too much hassle, let's just drop support of libxml2 < 2.9.9
