### ISSUE TITLE
goa publish failed

### ISSUE THREAD

**Issue by iloskutov** [genodelabs/goa#91]
Experimenting with depot and goa and have an issue on `goa publish`:
```
gpg: skipped "DA439C67842B4F25": No secret key
gpg: signing failed: No secret key
make: *** [/home/vanner/projects/genode/goa/share/goa/depot/publish:99: /home/vanner/projects/genode/waynit/genode/waynit/var/public/iloskutov/pkg/waynit/2024-02-15.tar.xz.sig] Error 1
make: *** Waiting for unfinished jobs....
[waynit] Error: failed to publish the following depot archives:
```

The issue is in the function `pubkey_id`. On my system gpg is configured by default with keyboxd.

**Comment by chelmuth** [comment]
> gpg: skipped "DA439C67842B4F25": No secret key

This key is *Genode Labs Depot 17.05 <depot@genode.org>*. You may only publish with a depot user that uses a pubkey of a seckey you possess yourself.

**Comment by iloskutov** [comment]
I know. And in my keyring it appears before my key. If gpg is configured with use-keyboxd, `--no-keyring` in the script doesn't work as expected.

**Comment by chelmuth** [comment]
Sorry, I discovered your PR #92 after writing my answer. May we close this issue in favor of the PR discussion?

**Comment by iloskutov** [comment]
Sure
