### ISSUE TITLE
Enable Meson support

### ISSUE THREAD

**Issue by ssumpf** [genodelabs/goa#94]
Some projects we ported or want to port have migrated to the [Meson](https://mesonbuild.com) build system (e.g., Mesa, Qemu, media driver, scrcpy). Therefore, it makes sense to enable Meson support in Goa.

**Comment by ssumpf** [comment]
[85d5686](https://github.com/ssumpf/goa/commit/85d56864786c8cc5a26571efd3eeab99ff2ed682) is a first step to support Meson:

* it supports x86_64 binaries only (no shared libraries) nor arm_v8a
* tested with https://github.com/ssumpf/goa-projects/tree/master/glmark2
* updated documentation
* added `hello_meson` test
* added `hello_meson` to _test.expect_

**Comment by jschlatow** [comment]
@ssumpf That's a valuable addition to Goa. Please have a look at my (few) inline comments.

**Comment by ssumpf** [comment]
@jschlatow: c89db8a adds a _pkg-config.tcl_ helper script and outputs the _used_api_ status during the
`setup` phase.

**Comment by ssumpf** [comment]
@jschlatow: I forgot to adjust a comment. Have a look add [c859273](https://github.com/ssumpf/goa/commit/c859273e34e2561dda6ce5f247f7bc8b8eaf0c01) instead please.

**Comment by jschlatow** [comment]
@ssumpf Thanks! I was also thinking about the issue with matching the required library names with the api names. Since there are api archives that produce multiple libraries (e.g. mesa, openssl), I was thinking about looking for lib.so files in var/abi/ instead of parsing the used_apis file. What's your opinion?

No matter what we do, we will only have a heuristic pkg-config emulation. I therefore like your idea about logging the pkg-config requests and printing the status.

**Comment by ssumpf** [comment]
> @ssumpf Thanks! I was also thinking about the issue with matching the required library names with the api names. Since there are api archives that produce multiple libraries (e.g. mesa, openssl), I was thinking about looking for lib.so files in var/abi/ instead of parsing the used_apis file. What's your opinion?

@jschlatow: Sounds more correct, so I will change that.

> No matter what we do, we will only have a heuristic pkg-config emulation. I therefore like your idea about logging the pkg-config requests and printing the status.

@jschlatow: True

**Comment by ssumpf** [comment]
@jschlatow: 17db994 searches for modules in var/abi.

**Comment by ssumpf** [comment]
@jschlatow: [adc537d](https://github.com/ssumpf/goa/commit/adc537dfc39ae1fa61bb6a3d888683d25a98dd5a) features the `lsearch` approach while I opted for an exact pattern.

**Comment by jschlatow** [comment]
Thanks. I merged your changes as 4b583dc and 2fd5e9b to staging.

**Comment by jschlatow** [comment]
The commits just entered the master branch.
