### ISSUE TITLE
add debugging support

### ISSUE THREAD

**Issue by jschlatow** [genodelabs/goa#95]

**Comment by jschlatow** [comment]
The above commit series implements support for handling dbg archives (download, export, publish) in Goa.

**Comment by nfeske** [comment]
Wow, that's simply amazing! I'm impressed how the concepts that evolved with the Sculpt-on-target debugging work are so well applicable to Goa.

**Comment by jschlatow** [comment]
> Wow, that's simply amazing! I'm impressed how the concepts that evolved with the Sculpt-on-target debugging work are so well applicable to Goa.

My next step is to integrate the debug monitor into goa testbed with the goal of running gdb on the local system and connect it to the remote Sculpt target. I'm curious how well this plays out. In this scenario, the separation of binaries and debug info is really beneficial. It would be quite annoying to wait for debug symbols being uploaded to the remote test system.

**Comment by nfeske** [comment]
The solution seems to fall so natural into place. If it works out as you intend, this will rock!

**Comment by ssumpf** [comment]
This looks really useful :+1:

**Comment by jschlatow** [comment]
The changes entered the master branch. Detailed instructions will soon be available on [genodians.org](https://genodians.org/jschlatow/2024-07-31-goa-gdb).
